name: Build frontend

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - 'expense-frontend/**'
  pull_request:
    branches:
      - "**"
    paths:
      - 'expense-frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-expense-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expense-frontend

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './expense-frontend/package-lock.json'
      - name: Install dependencies
        run: cd ./expense-frontend && npm ci

      - name: Build frontend
        run: npm run build --if-present
      - name: Test frontend
        run: npm test

  docker-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./expense-frontend
          file: ./expense-frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
